networks:
  springbootapp-network:
    driver: bridge
services:
  backend:
    build: .
    container_name: backend
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - springbootapp-network
    environment:
      - DATABASE_HOST=db # redefines localhost in .env file
  db:
    image: postgres:18
    container_name: db
    restart: always
    shm_size: 128mb # set shared memory limit when using docker compose
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - springbootapp-network
  activemq:
    image: apache/activemq:5.19.2
    container_name: activemq
    ports:
      - "1099:1099" # ActiveMQ JMX MBean server
      - "1883:1883" # ActiveMQ MQTT connector
      - "5672:5672" # ActiveMQ AMQP connector
      - "8161:8161" # ActiveMQ WebConsole!
      - "61613:61613" # ActiveMQ STOMP connector
      - "61614:61614" # ActiveMQ WS connector
      - "61616:61616" # ActiveMQ tcp connector!
    networks:
      - springbootapp-network

