spring:
  config:
    import: optional:file:.env[.properties]
  task:
    scheduling:
      pool:
        size: 5
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
  jpa:
    open-in-view: false
#    show-sql: true # show sql statements
    hibernate:
      ddl-auto: create # Creates the schema and destroys previous data
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.default_schema: ${DATABASE_SCHEMA}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?${DATABASE_PROPERTIES}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  activemq:
    embedded:
      enabled: false
#    broker-url: tcp://localhost:61616
#    user:
#    password:
#  jms:
#    client-id: springbootapp
#    subscription-durable: false
ACTIVE_MQ_URL: tcp://${ACTIVE_MQ_HOST}:${ACTIVE_MQ_PORT}